// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.my.demo.Demo;

public interface TestServicePrx extends Ice.ObjectPrx
{
    public byte[] getData(byte[] bytes, int len);

    public byte[] getData(byte[] bytes, int len, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, Ice.Callback __cb);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, Callback_TestService_getData __cb);

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx, Callback_TestService_getData __cb);

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public byte[] end_getData(Ice.AsyncResult __result);
}
