// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.my.demo.Demo;

public interface TestService extends Ice.Object,
                                     _TestServiceOperations, _TestServiceOperationsNC
{
    public static final String ice_staticId = "::Demo::TestService";

    public static final long serialVersionUID = 1097100181L;
}
