// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.my.demo.Demo;

/**
 * Provides type-specific helper functions.
 **/
public final class TestServicePrxHelper extends Ice.ObjectPrxHelperBase implements TestServicePrx
{
    private static final String __getData_name = "getData";

    public byte[] getData(byte[] bytes, int len)
    {
        return getData(bytes, len, null, false);
    }

    public byte[] getData(byte[] bytes, int len, java.util.Map<String, String> __ctx)
    {
        return getData(bytes, len, __ctx, true);
    }

    private byte[] getData(byte[] bytes, int len, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__getData_name);
        return end_getData(begin_getData(bytes, len, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len)
    {
        return begin_getData(bytes, len, null, false, false, null);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx)
    {
        return begin_getData(bytes, len, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, Ice.Callback __cb)
    {
        return begin_getData(bytes, len, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getData(bytes, len, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, Callback_TestService_getData __cb)
    {
        return begin_getData(bytes, len, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, int len, java.util.Map<String, String> __ctx, Callback_TestService_getData __cb)
    {
        return begin_getData(bytes, len, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getData(bytes, len, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getData(bytes, len, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getData(bytes, len, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getData(byte[] bytes, 
                                         int len, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getData(bytes, len, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_getData(byte[] bytes, 
                                          int len, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_GenericCallback1<byte[]> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getData(bytes, len, __ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackArg1<byte[]>(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         TestServicePrxHelper.__getData_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_getData(byte[] bytes, 
                                          int len, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getData_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__getData_name, __cb);
        try
        {
            __result.prepare(__getData_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            WuBytesHelper.write(__os, bytes);
            __os.writeInt(len);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public byte[] end_getData(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getData_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            byte[] __ret;
            __ret = WuBytesHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __getData_completed(Ice.TwowayCallbackArg1<byte[]> __cb, Ice.AsyncResult __result)
    {
        com.my.demo.Demo.TestServicePrx __proxy = (com.my.demo.Demo.TestServicePrx)__result.getProxy();
        byte[] __ret = null;
        try
        {
            __ret = __proxy.end_getData(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), TestServicePrx.class, TestServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), TestServicePrx.class, TestServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), TestServicePrx.class, TestServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), TestServicePrx.class, TestServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static TestServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, TestServicePrx.class, TestServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static TestServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, TestServicePrx.class, TestServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Demo::TestService",
        "::Ice::Object"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[0];
    }

    public static void __write(IceInternal.BasicStream __os, TestServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static TestServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            TestServicePrxHelper result = new TestServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
