// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <demo.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Demo__TestService__getData_name = "getData";

}
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(::IceProxy::Demo::TestService* p) { return p; }

void
::IceProxy::Demo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Demo::TestService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Demo::TestService;
        v->__copyFrom(proxy);
    }
}

::Demo::WuBytes
IceProxy::Demo::TestService::getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Demo__TestService__getData_name);
    ::IceInternal::Outgoing __og(this, __Demo__TestService__getData_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_bytes);
        __os->write(__p_len);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::Demo::WuBytes __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Demo::TestService::begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Demo__TestService__getData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Demo__TestService__getData_name, __del, __cookie);
    try
    {
        __result->prepare(__Demo__TestService__getData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_bytes);
        __os->write(__p_len);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Demo::TestService::__begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Demo::WuBytes&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::Demo::WuBytes&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Demo::TestServicePrx __proxy = ::Demo::TestServicePrx::uncheckedCast(__result->getProxy());
            ::Demo::WuBytes __ret;
            try
            {
                __ret = __proxy->end_getData(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::Demo::WuBytes&)> _response;
    };
    return begin_getData(__p_bytes, __p_len, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::Demo::WuBytes
IceProxy::Demo::TestService::end_getData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Demo__TestService__getData_name);
    ::Demo::WuBytes __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::Demo::TestService::ice_staticId()
{
    return ::Demo::TestService::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Demo::TestService::__newInstance() const
{
    return new TestService;
}

::Ice::Object* Demo::upCast(::Demo::TestService* p) { return p; }

namespace
{
const ::std::string __Demo__TestService_ids[2] =
{
    "::Demo::TestService",
    "::Ice::Object"
};

}

bool
Demo::TestService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Demo__TestService_ids, __Demo__TestService_ids + 2, _s);
}

::std::vector< ::std::string>
Demo::TestService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Demo__TestService_ids[0], &__Demo__TestService_ids[2]);
}

const ::std::string&
Demo::TestService::ice_id(const ::Ice::Current&) const
{
    return __Demo__TestService_ids[0];
}

const ::std::string&
Demo::TestService::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::TestService";
    return typeId;
#else
    return __Demo__TestService_ids[0];
#endif
}

::Ice::DispatchStatus
Demo::TestService::___getData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Demo::WuBytes __p_bytes;
    ::Ice::Int __p_len;
    __is->read(__p_bytes);
    __is->read(__p_len);
    __inS.endReadParams();
    ::Demo::WuBytes __ret = getData(__p_bytes, __p_len, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Demo__TestService_all[] =
{
    "getData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Demo::TestService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Demo__TestService_all, __Demo__TestService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Demo__TestService_all)
    {
        case 0:
        {
            return ___getData(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Demo::TestService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Demo::TestService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Demo::__patch(TestServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Demo::TestServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Demo::TestService::ice_staticId(), v);
    }
}
