// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __demo_h__
#define __demo_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Demo
{

class TestService;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::TestService>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::TestService*);

}

}

namespace Demo
{

class TestService;
::Ice::Object* upCast(::Demo::TestService*);
typedef ::IceInternal::Handle< ::Demo::TestService> TestServicePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::TestService> TestServicePrx;
void __patch(TestServicePtr&, const ::Ice::ObjectPtr&);

}

namespace Demo
{

typedef ::std::vector< ::Ice::Byte> WuBytes;

}

namespace Demo
{

class Callback_TestService_getData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TestService_getData_Base> Callback_TestService_getDataPtr;

}

namespace IceProxy
{

namespace Demo
{

class TestService : virtual public ::IceProxy::Ice::Object
{
public:

    ::Demo::WuBytes getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len)
    {
        return getData(__p_bytes, __p_len, 0);
    }
    ::Demo::WuBytes getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx)
    {
        return getData(__p_bytes, __p_len, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::IceInternal::Function<void (const ::Demo::WuBytes&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getData(__p_bytes, __p_len, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getData(__p_bytes, __p_len, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Demo::WuBytes&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getData(__p_bytes, __p_len, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getData(__p_bytes, __p_len, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Demo::WuBytes&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len)
    {
        return begin_getData(__p_bytes, __p_len, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx)
    {
        return begin_getData(__p_bytes, __p_len, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getData(__p_bytes, __p_len, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getData(__p_bytes, __p_len, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Demo::Callback_TestService_getDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getData(__p_bytes, __p_len, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& __p_bytes, ::Ice::Int __p_len, const ::Ice::Context& __ctx, const ::Demo::Callback_TestService_getDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getData(__p_bytes, __p_len, &__ctx, __del, __cookie);
    }

    ::Demo::WuBytes end_getData(const ::Ice::AsyncResultPtr&);
    
private:

    ::Demo::WuBytes getData(const ::Demo::WuBytes&, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes&, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<TestService> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_secure(bool __secure) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_twoway() const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_oneway() const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_batchOneway() const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_datagram() const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_batchDatagram() const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_compress(bool __compress) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_timeout(int __timeout) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TestService> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<TestService*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Demo
{

class TestService : virtual public ::Ice::Object
{
public:

    typedef TestServicePrx ProxyType;
    typedef TestServicePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Demo::WuBytes getData(const ::Demo::WuBytes&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const TestService& l, const TestService& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const TestService& l, const TestService& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Demo
{

template<class T>
class CallbackNC_TestService_getData : public Callback_TestService_getData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Demo::WuBytes&);

    CallbackNC_TestService_getData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::TestServicePrx __proxy = ::Demo::TestServicePrx::uncheckedCast(__result->getProxy());
        ::Demo::WuBytes __ret;
        try
        {
            __ret = __proxy->end_getData(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_TestService_getDataPtr
newCallback_TestService_getData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::WuBytes&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TestService_getData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TestService_getDataPtr
newCallback_TestService_getData(T* instance, void (T::*cb)(const ::Demo::WuBytes&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TestService_getData<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_TestService_getData : public Callback_TestService_getData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Demo::WuBytes&, const CT&);

    Callback_TestService_getData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::TestServicePrx __proxy = ::Demo::TestServicePrx::uncheckedCast(__result->getProxy());
        ::Demo::WuBytes __ret;
        try
        {
            __ret = __proxy->end_getData(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_TestService_getDataPtr
newCallback_TestService_getData(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::WuBytes&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TestService_getData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TestService_getDataPtr
newCallback_TestService_getData(T* instance, void (T::*cb)(const ::Demo::WuBytes&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TestService_getData<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
