// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __demo_h__
#define __demo_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace Demo
{

class TestService;
class TestServicePrx;

}

namespace Demo
{

using WuBytes = ::std::vector<::Ice::Byte>;

}

namespace Demo
{

class TestService : public virtual ::Ice::Object
{
public:

    using ProxyType = TestServicePrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual WuBytes getData(WuBytes bytes, int len, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace Demo
{

class TestServicePrx : public virtual ::Ice::Proxy<TestServicePrx, ::Ice::ObjectPrx>
{
public:

    WuBytes getData(const WuBytes& bytes, int len, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<WuBytes>(true, this, &TestServicePrx::_iceI_getData, bytes, len, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getDataAsync(const WuBytes& bytes, int len, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<WuBytes>>().get_future())
    {
        return _makePromiseOutgoing<WuBytes, P>(false, this, &TestServicePrx::_iceI_getData, bytes, len, context);
    }

    ::std::function<void()>
    getDataAsync(const WuBytes& bytes, int len,
                 ::std::function<void(WuBytes)> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<WuBytes>(response, ex, sent, this, &TestServicePrx::_iceI_getData, bytes, len, context);
    }

    /// \cond INTERNAL
    void _iceI_getData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<WuBytes>>&, const WuBytes&, int, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    TestServicePrx() = default;
    friend ::std::shared_ptr<TestServicePrx> IceInternal::createProxy<TestServicePrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace Demo
{

using TestServicePtr = ::std::shared_ptr<TestService>;
using TestServicePrxPtr = ::std::shared_ptr<TestServicePrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace Demo
{

class TestService;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::TestService>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::TestService*);
/// \endcond

}

}

namespace Demo
{

class TestService;
/// \cond INTERNAL
::Ice::Object* upCast(TestService*);
/// \endcond
typedef ::IceInternal::Handle< TestService> TestServicePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::TestService> TestServicePrx;
typedef TestServicePrx TestServicePrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(TestServicePtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace Demo
{

typedef ::std::vector<Ice::Byte> WuBytes;

}

namespace Demo
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::Demo::TestService::begin_getData.
 * Create a wrapper instance by calling ::Demo::newCallback_TestService_getData.
 */
class Callback_TestService_getData_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TestService_getData_Base> Callback_TestService_getDataPtr;

}

namespace IceProxy
{

namespace Demo
{

class TestService : public virtual ::Ice::Proxy<TestService, ::IceProxy::Ice::Object>
{
public:

    ::Demo::WuBytes getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getData(_iceI_begin_getData(bytes, len, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getData(bytes, len, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getData(bytes, len, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getData(bytes, len, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Demo::Callback_TestService_getDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getData(bytes, len, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getData(const ::Demo::WuBytes& bytes, ::Ice::Int len, const ::Ice::Context& context, const ::Demo::Callback_TestService_getDataPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getData(bytes, len, context, cb, cookie);
    }

    ::Demo::WuBytes end_getData(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getData(const ::Demo::WuBytes&, ::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace Demo
{

class TestService : public virtual ::Ice::Object
{
public:

    typedef TestServicePrx ProxyType;
    typedef TestServicePtr PointerType;

    virtual ~TestService();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual WuBytes getData(const WuBytes& bytes, ::Ice::Int len, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getData(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const TestService& lhs, const TestService& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const TestService& lhs, const TestService& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace Demo
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::Demo::TestService::begin_getData.
 * Create a wrapper instance by calling ::Demo::newCallback_TestService_getData.
 */
template<class T>
class CallbackNC_TestService_getData : public Callback_TestService_getData_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const WuBytes&);

    CallbackNC_TestService_getData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        TestServicePrx proxy = TestServicePrx::uncheckedCast(result->getProxy());
        WuBytes ret;
        try
        {
            ret = proxy->end_getData(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::Demo::TestService::begin_getData.
 */
template<class T> Callback_TestService_getDataPtr
newCallback_TestService_getData(const IceUtil::Handle<T>& instance, void (T::*cb)(const WuBytes&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TestService_getData<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::Demo::TestService::begin_getData.
 */
template<class T> Callback_TestService_getDataPtr
newCallback_TestService_getData(T* instance, void (T::*cb)(const WuBytes&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TestService_getData<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::Demo::TestService::begin_getData.
 * Create a wrapper instance by calling ::Demo::newCallback_TestService_getData.
 */
template<class T, typename CT>
class Callback_TestService_getData : public Callback_TestService_getData_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const WuBytes&, const CT&);

    Callback_TestService_getData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        TestServicePrx proxy = TestServicePrx::uncheckedCast(result->getProxy());
        WuBytes ret;
        try
        {
            ret = proxy->end_getData(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::Demo::TestService::begin_getData.
 */
template<class T, typename CT> Callback_TestService_getDataPtr
newCallback_TestService_getData(const IceUtil::Handle<T>& instance, void (T::*cb)(const WuBytes&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TestService_getData<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::Demo::TestService::begin_getData.
 */
template<class T, typename CT> Callback_TestService_getDataPtr
newCallback_TestService_getData(T* instance, void (T::*cb)(const WuBytes&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TestService_getData<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
