// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <demo.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Demo_TestService_ids[2] =
{
    "::Demo::TestService",
    "::Ice::Object"
};
const ::std::string iceC_Demo_TestService_ops[] =
{
    "getData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Demo_TestService_getData_name = "getData";

}

bool
Demo::TestService::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_TestService_ids, iceC_Demo_TestService_ids + 2, s);
}

::std::vector<::std::string>
Demo::TestService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Demo_TestService_ids[0], &iceC_Demo_TestService_ids[2]);
}

::std::string
Demo::TestService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::TestService::ice_staticId()
{
    static const ::std::string typeId = "::Demo::TestService";
    return typeId;
}

/// \cond INTERNAL
bool
Demo::TestService::_iceD_getData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    WuBytes iceP_bytes;
    int iceP_len;
    istr->readAll(iceP_bytes, iceP_len);
    inS.endReadParams();
    WuBytes ret = this->getData(::std::move(iceP_bytes), iceP_len, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Demo::TestService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_TestService_ops, iceC_Demo_TestService_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_TestService_ops)
    {
        case 0:
        {
            return _iceD_getData(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
Demo::TestServicePrx::_iceI_getData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<WuBytes>>& outAsync, const WuBytes& iceP_bytes, int iceP_len, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Demo_TestService_getData_name);
    outAsync->invoke(iceC_Demo_TestService_getData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_bytes, iceP_len);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Demo::TestServicePrx::_newInstance() const
{
    return ::IceInternal::createProxy<TestServicePrx>();
}
/// \endcond

const ::std::string&
Demo::TestServicePrx::ice_staticId()
{
    return TestService::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Demo_TestService_getData_name = "getData";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(TestService* p) { return p; }

void
::IceProxy::Demo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< TestService>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new TestService;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Demo::TestService::_iceI_begin_getData(const ::Demo::WuBytes& iceP_bytes, ::Ice::Int iceP_len, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Demo_TestService_getData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Demo_TestService_getData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Demo_TestService_getData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_bytes);
        ostr->write(iceP_len);
        result->endWriteParams();
        result->invoke(iceC_Demo_TestService_getData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Demo::WuBytes
IceProxy::Demo::TestService::end_getData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Demo_TestService_getData_name);
    ::Demo::WuBytes ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Demo::TestService::_newInstance() const
{
    return new TestService;
}
/// \endcond

const ::std::string&
IceProxy::Demo::TestService::ice_staticId()
{
    return ::Demo::TestService::ice_staticId();
}

Demo::TestService::~TestService()
{
}

/// \cond INTERNAL
::Ice::Object* Demo::upCast(TestService* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Demo_TestService_ids[2] =
{
    "::Demo::TestService",
    "::Ice::Object"
};

}

bool
Demo::TestService::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_TestService_ids, iceC_Demo_TestService_ids + 2, s);
}

::std::vector< ::std::string>
Demo::TestService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Demo_TestService_ids[0], &iceC_Demo_TestService_ids[2]);
}

const ::std::string&
Demo::TestService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::TestService::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::TestService";
    return typeId;
#else
    return iceC_Demo_TestService_ids[0];
#endif
}

/// \cond INTERNAL
bool
Demo::TestService::_iceD_getData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    WuBytes iceP_bytes;
    ::Ice::Int iceP_len;
    istr->read(iceP_bytes);
    istr->read(iceP_len);
    inS.endReadParams();
    WuBytes ret = this->getData(iceP_bytes, iceP_len, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Demo_TestService_all[] =
{
    "getData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Demo::TestService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_TestService_all, iceC_Demo_TestService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_TestService_all)
    {
        case 0:
        {
            return _iceD_getData(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Demo::TestService::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< TestService, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Demo::TestService::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< TestService, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Demo::_icePatchObjectPtr(TestServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = TestServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(TestService::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
